create table if not exists "FantasyCalcPlayerValues" (
    "id" bigint generated by default as identity primary key,
    "player_id" bigint not null references "Players"("id") on delete cascade,
    "mode" text not null default 'DYN',
    "num_teams" smallint not null,
    "num_qbs" smallint not null,
    "ppr" numeric(2,1) not null,
    "te_premium" text not null default 'NOTEP',
    "fantasy_calc_player_id" integer not null,
    "value" integer not null,
    "overall_rank" integer not null,
    "position_rank" integer not null,
    "updated_at" timestamptz not null default now(),
    constraint "FantasyCalcPlayerValues_mode_check" check ("mode" = 'DYN'),
    constraint "FantasyCalcPlayerValues_num_teams_check" check ("num_teams" in (8, 10, 12, 14)),
    constraint "FantasyCalcPlayerValues_num_qbs_check" check ("num_qbs" in (1, 2)),
    constraint "FantasyCalcPlayerValues_ppr_check" check ("ppr" in (0.0, 0.5, 1.0)),
    constraint "FantasyCalcPlayerValues_te_premium_check" check ("te_premium" in ('NOTEP', 'TEP', 'TEPPLUS')),
    constraint "FantasyCalcPlayerValues_player_mode_format_key" unique ("player_id", "mode", "num_teams", "num_qbs", "ppr", "te_premium")
);

create index if not exists "FantasyCalcPlayerValues_format_idx" on "FantasyCalcPlayerValues" ("mode", "num_teams", "num_qbs", "ppr", "te_premium");

alter table "FantasyCalcPlayerValues" enable row level security;